### PR TITLE
nix flake update

### PR DESCRIPTION
**Pull request by matthiasbeyer**
I guess dependabot is not yet able to do this, so here's a PR for it.

### CODE REVIEW

**Comment by TheNeikos** [comment]
I am not opposed to updating this file. However, I don’t think it should be done just for the sake of it. For example the rust-overlay is updated every day. Mostly to get the latest nightly version.

**Comment by matthiasbeyer** [comment]
The action in use here is also able to only update some of the inputs. How about a weekly update for the `nixpkgs`, `flake-utils` and `crane` inputs here and a monthly one for the `rust-overlay` one?

**Comment by TheNeikos** [comment]
I changed my mind on allowing updates to `nixpkgs`, this way security updates etc are included. Since all other inputs are made to follow nixpkgs this will also update theirs.

**Comment by TheNeikos** [comment]
Thanks!

bors r+

**Pull request merged**
