### PR TITLE
Add markdown renderer: patches

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by TheNeikos** [comment]
Needs to be rebased now

**Comment by matthiasbeyer** [comment]
Why? This PRs base-branch did not move AFAICS!

**Comment by TheNeikos** [comment]
So the CI runs afaik?

**Comment by matthiasbeyer** [comment]
Ah. Yes sure! But this is not based off of main, but your `feature/add_mardown_renderer`, so I guess you'd have to rebase and then either cherry-pick these patches, or I have to rebase my PR to your PR after your PR was rebased :laughing:

**Pull request closed without merging**
