### PR TITLE
Add AsTypeDescription impl for human_repr types

### LINKED ISSUE #169: human_repr implementation?
It seems that the `human_repr` crate does [not support serde](https://docs.rs/human-repr/latest/human_repr/struct.HumanCountData.html).

Do we still want an implementation of `AsTypeDescription` for its types? Also, we might want to feature-request serde support in the `human_repr` crate...

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Closes #169

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
I somehow got things a bit wrong... the `human_repr` crate does not support _parsing_ these,... which I thought it would.

I requested this functionality here: https://github.com/rsalmei/human-repr/issues/4

But before this is implemented, we can postpone this PR I think.

**Comment by matthiasbeyer** [comment]
human_repr got the `serde` feature in `1.1`, so this is now rebased and contains the crate in `1.1` with `serde` enabled.

**Comment by TheNeikos** [comment]
What happens if you put `1.0000028s` with the `human_repr` crate? From what I read, it would _not_ give you exactly that count, but instead round it, making it just `1`. I would not consider this applicable for configuration use, where the precision of the user could very much matter.


I would accept the PR if it can be shown that:

- Precision can optionally not be lost when parsing & printing
- Tests that check that property, to make sure potential bugs don't get through

**Comment by matthiasbeyer** [comment]
Yeah now that I look at the code of the crate, they even implemented serde compatibility not as I intended. :disappointed: 

I think we can close this issue, as depending on the `human_repr` crate seems not to be a good idea.

**Comment by rsalmei** [comment]
Hi @TheNeikos,
I'm the author of https://github.com/rsalmei/human-repr.
This use as "configuration" was never intended, human-repr was conceived to generate human representations for user messages, but I'm kinda linking this idea now...
I'm working on it, thinking about how I could make it parse things and allow one to write config files with these human representations, so this may be a reality soon.

> * Precision can optionally not be lost when parsing & printing

Of course in a configuration system precision is mandatory, rest assured I'm thinking about this.
What I'm worried about are units that might clash with prefixes.
See, on `123MCrabs` it is obvious that we have `123 million` of `Crabs`.
But what about `123Transactions`? Is it `123` of `Transactions` or `123 billion` of `ransactions`? The "T" is the Tera prefix... I'm not sure how I'll resolve this.

Anyway, the issue @matthiasbeyer opened there on [my crate](https://github.com/rsalmei/human-repr/issues/4) is opened, so I expect this could be reopened too.
Thanks.

**Comment by TheNeikos** [comment]
Heya @rsalmei thanks for the notice. I appreciate the heads up, and I am definitely interested in integrating it with the changes you've suggested.

WRT to the units, you could maybe specify it as `123T Transactions` or something, aka have a mandatory space between value+multiplier and unit?

**Pull request closed without merging**
